// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_BXMBvM3h8onEIKqeJ8U1Z62jd8MM7Q8',
    appId: '1:101465307454:web:3a6474a99d73b1e4f5546f',
    messagingSenderId: '101465307454',
    projectId: 'gr09-astrovibe-2025',
    authDomain: 'gr09-astrovibe-2025.firebaseapp.com',
    storageBucket: 'gr09-astrovibe-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNEDniGrt_CzDLwP7HWpfDuP-CCnHp3RA',
    appId: '1:101465307454:android:8310c5a1e9335f92f5546f',
    messagingSenderId: '101465307454',
    projectId: 'gr09-astrovibe-2025',
    storageBucket: 'gr09-astrovibe-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJSpghHYlJnMP2TsfjPR98dm5mwmkG0Y4',
    appId: '1:101465307454:ios:a8aeefe3b2575f8ef5546f',
    messagingSenderId: '101465307454',
    projectId: 'gr09-astrovibe-2025',
    storageBucket: 'gr09-astrovibe-2025.firebasestorage.app',
    iosBundleId: 'com.example.astroVibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJSpghHYlJnMP2TsfjPR98dm5mwmkG0Y4',
    appId: '1:101465307454:ios:a8aeefe3b2575f8ef5546f',
    messagingSenderId: '101465307454',
    projectId: 'gr09-astrovibe-2025',
    storageBucket: 'gr09-astrovibe-2025.firebasestorage.app',
    iosBundleId: 'com.example.astroVibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_BXMBvM3h8onEIKqeJ8U1Z62jd8MM7Q8',
    appId: '1:101465307454:web:35b0403c6a1a3234f5546f',
    messagingSenderId: '101465307454',
    projectId: 'gr09-astrovibe-2025',
    authDomain: 'gr09-astrovibe-2025.firebaseapp.com',
    storageBucket: 'gr09-astrovibe-2025.firebasestorage.app',
  );
}
