name: Build and Distribute Android App to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build-and-distribute:
    name: Build and Distribute Android App to Firebase
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build release APK
      run: flutter build apk --release
      
    - name: Install Firebase CLI
      run: |
        curl -sL https://firebase.tools | bash
        
    - name: Distribute APK to Firebase App Distribution
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --groups "testers" \
          --release-notes "Automated build from GitHub Actions - Commit: ${{ github.sha }}"
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk 